### ISSUE TITLE
Error with service

### ISSUE THREAD

**Issue by beexo-si** [rsksmart/rsk-explorer-api#45]
**Preconditions**

OS: Ubuntu 18.04
Node: v13.3.0
Mongo: v4.2.1
RSK Node: Testnet

**Steps to reproduce**

- Install
- Run node dist/services/blocks

**Actual result**

After a few minutes running, throws this error:

```
events.js:196
      throw er; // Unhandled 'error' event
      ^
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:204:27)
Emitted 'error' event on ClientRequest instance at:
    at Socket.socketErrorListener (_http_client.js:420:9)
    at Socket.emit (events.js:219:5)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}
events.js:196
      throw er; // Unhandled 'error' event
      ^
...

Error: socket hang up
    at connResetException (internal/errors.js:581:14)
    at Socket.socketOnEnd (_http_client.js:451:23)
    at Socket.emit (events.js:224:7)
    at endReadableNT (_stream_readable.js:1206:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ClientRequest instance at:
    at Socket.socketOnEnd (_http_client.js:451:9)
    at Socket.emit (events.js:224:7)
    at endReadableNT (_stream_readable.js:1206:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ECONNRESET'
}
```

Before restarting the service, it happens again:

```
Error: connect ECONNREFUSED 127.0.0.1:4444
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1136:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 4444
}

```

**Comment by emiliorizzo** [comment]
The error says that the rskj node is not responding on 127.0.0.1:4444.
Please check if the node is listening and responding. And try again. 
```
curl -H "Content-Type":"application/json" -X POST -d '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest",false],"id":1}' http://localhost:4444
```
Thanks

**Comment by beexo-si** [comment]
The problem was that the service was overloading the RSK node. The solution was to resize the node server to one with more RAM and CPU

**Comment by emiliorizzo** [comment]
The service was overloading the node or the node was overloading the service? :)
